image: ruby:latest

pages:
  script:
  - bundle install
  - bundle exec jekyll build -d public
  - git clone https://github.com/google/zopfli.git && cd zopfli && gcc src/zopfli/*.c -O2 -W -Wall -Wextra -Wno-unused-function -ansi -pedantic -lm -o zopfli && ./zopfli $(find public -type f)
  artifacts:
    paths:
    - public
