image: ruby:latest

pages:
  script:
  - bundle install
  - bundle exec jekyll build -d public
  - cp public/index.html public/404.html
  - git clone https://github.com/google/zopfli.git && cd zopfli && gcc src/zopfli/*.c -O2 -W -Wall -Wextra -Wno-unused-function -ansi -pedantic -lm -o zopfli && ./zopfli $(find ../public -type f)
  artifacts:
    paths:
    - public
https:
  script:
    - echo $OPENSSL_CONFIG > openssl.cnf
    - openssl req -new -sha256 -key $DOMAIN_KEY -subj "/" -reqexts SAN -config openssl.cnf -out csr.csr
    - git clone https://github.com/diafygi/acme-tiny.git
    - python acme_tiny/acme_tiny.py --account-key $ACCOUNT_KEY --csr csr.csr --acme-dir public/.well-known/acme-challenge/ > cert.pem
    - "curl --request PUT --header \"Private-Token: $GITLAB_TOKEN\" --form \"certificate=cert.pem\" --form \"key=$DOMAIN_KEY\" https://framagit.org/api/v4/projects/$CI_PROJECT_ID/pages/domains/$DOMAIN"

