title: Mathias
description: My name is Mathias. I like to contribute to various software projects I find interesting. This is my personal website, which I use for different projects and experiments of mine.
url: https://mathias.re

exclude:
  - build.sh
  - Gemfile
  - LICENSE

jekyll-minifier:
  remove_intertag_spaces: true
  remove_quotes: true

sass:
  style: :compressed
