title: Mathias
description: My name is Mathias. I like to mess around with web design and software development in my free time.
url: https://mathias.is

exclude:
  - build.sh
  - Gemfile
  - LICENSE

sass:
  style: :compressed
