title: Mathias
description: My name is Mathias. I like to contribute to software projects that interest me. This is my personal website, which I use for various experiments of mine.
url: https://mathias.re

exclude:
  - build.sh
  - Gemfile
  - LICENSE

sass:
  style: :compressed
