title: Mathias
description: Personal website for Mathias
url: https://mathias.re

markdown: kramdown
sass:
  style: :compressed
gems:
  - jekyll-sitemap
include:
  - _headers
exclude:
  - Gemfile
  - Gemfile.lock