title: Mathias
description: My name is Mathias. I like to mess around with technology in my free time, whether it be web design or software development.
url: https://mathias.re

exclude:
  - build.sh
  - Gemfile
  - LICENSE

sass:
  style: :compressed
