title: Mathias
description: My name is Mathias. This is my personal website, which I use for various experiments.
url: https://mathias.re

sass:
  style: :compressed
include:
  - _headers
exclude:
  - Gemfile
  - Gemfile.lock
