title: Mathias
description: My name is Mathias. This is my personal website, which I use for various experiments.
url: https://mathias.re

exclude:
  - build.sh
  - Gemfile
  - LICENSE

jekyll-minifier:
  remove_intertag_spaces: true
  remove_quotes: true

sass:
  style: :compressed
