title: Mathias
description: Mathias is the name. Simply another personal website.
url: "&#x68;&#x74;&#x74;&#x70;&#x73;&#x3A;&#x2F;&#x2F;&#x6D;&#x61;&#x74;&#x68;&#x69;&#x61;&#x73;&#x2E;&#x69;&#x73;"
theme: null

exclude:
  - Gemfile
  - LICENSE
  - README.md

sass:
  style: :compressed
