[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = "connect-src 'none'; default-src 'none'; font-src data:; frame-src 'none'; img-src 'none'; media-src 'none'; object-src 'none'; script-src 'none'; style-src 'self'"
Referrer-Policy = "no-referrer"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"

[[headers]]
for = "/*.css"
[headers.values]
Cache-Control = "max-age=604800"
Expires: 604800

[[redirects]]
from = "/*"
to = "/index"
